// Code generated by `yo/srv/codegen_apistuff.go` DO NOT EDIT
package appdemo

import reflect "reflect"
import yosrv "yo/srv"
import util "yo/util"
import q "yo/db/query"

type _ = q.F // just in case of no other generated import users
type apiPkgInfo util.None

func (apiPkgInfo) PkgName() string    { return "appdemo" }
func (me apiPkgInfo) PkgPath() string { return reflect.TypeOf(me).PkgPath() }

var appdemoPkg = apiPkgInfo{}

func api[TIn any, TOut any](f func(*yosrv.ApiCtx[TIn, TOut]), failIfs ...yosrv.Fails) yosrv.ApiMethod {
	return yosrv.Api[TIn, TOut](f, failIfs...).From(appdemoPkg)
}

const Err__helloName_ExpectedName util.Err = "__helloName_ExpectedName"
const __helloNameName = q.F("Name")
